version: "3.7"
services:

  php:
    build:
      context: ./docker/images/php
      args:
        php_version: ${PHP_VERSION}
        set_up_ssh_server: ${SET_UP_SSH_SERVER}
    volumes:
      - ./docker/logs/tmp/php_sessions:/sessions
      - logs:/var/log
      - project:/var/www
    ports:
      - "${INTERFACE}:${PHP_FPM_PORT}:9000"
      - "${INTERFACE}:${XDEBUG_PORT}:9001"
      - "${INTERFACE}:${SSH_PORT}:22"
    environment:
      XDEBUG_CONFIG: "remote_host=${XDEBUG_HOST} remote_enable=${XDEBUG_REMOTE_ENABLE} remote_connect_back=${XDEBUG_CONNECT_BACK}"

  nginx:
    build: ./docker/images/nginx
    volumes:
      - project:/var/www
    links:
      - php
    ports:
      - "80:80"
      - "443:443"

volumes:
  project:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PROJECT_PATH}
  logs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${LOGS_PATH}
